version: 2.1
executors:
  docker-publish:
    environment:
      BUILDER_NAME: openioci/builder
      RUNTIME_NAME: openioci/runtime
    docker:
      - image: circleci/buildpack-deps:bionic-scm
jobs:
  build:
    executor: docker-publish
    steps:
      - checkout
      - run:
          name: Submodule update
          command: |
            git submodule sync
            git submodule update --init
      - setup_remote_docker
      - run:
          name: Build
          command: |
            docker pull $BUILDER_NAME:latest || true
            docker build --cache-from $BUILDER_NAME:latest -t $BUILDER_NAME .
      - run:
          name: Install s2i
          command: curl -L https://github.com/openshift/source-to-image/releases/download/v1.1.14/source-to-image-v1.1.14-874754de-linux-amd64.tar.gz | tar xz ./s2i && sudo install s2i /usr/local/bin/s2i
      - run:
          name: Test
          command: make test
      - run:
          name: Save images
          command: |
            docker save $BUILDER_NAME | gzip > builder.tar.gz
            docker save $RUNTIME_NAME | gzip > runtime.tar.gz
      - persist_to_workspace:
          root: .
          paths:
            - ./builder.tar.gz
            - ./runtime.tar.gz
  publish:
    executor: docker-publish
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load images
          command: |
            docker load -i /tmp/workspace/builder.tar.gz
            docker load -i /tmp/workspace/runtime.tar.gz
      - run:
          name: Push image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            IMAGE_TAG="${CIRCLE_BUILD_NUM}"
            docker tag $BUILDER_NAME:latest $BUILDER_NAME:$IMAGE_TAG
            docker push $BUILDER_NAME:latest
            docker push $BUILDER_NAME:$IMAGE_TAG
            docker push $RUNTIME_NAME:latest

workflows:
  version: 2
  main:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
