version: 2.1
executors:
  docker-publish:
    environment:
      IMAGE_NAME: openioci/builder
    docker:
      - image: circleci/buildpack-deps:bionic-scm
jobs:
  build:
    executor: docker-publish
    steps:
      - checkout
      - run:
          name: Submodule update
          command: |
            git submodule sync
            git submodule update --init
      - setup_remote_docker
      - run:
          name: Build
          command: |
            docker pull $IMAGE_NAME:latest || true
            docker build --cache-from $IMAGE_NAME:latest -t $IMAGE_NAME .
      - run:
          name: Install s2i
          command: curl -L https://github.com/openshift/source-to-image/releases/download/v1.1.14/source-to-image-v1.1.14-874754de-linux-amd64.tar.gz | tar xz ./s2i && sudo install s2i /usr/local/bin/s2i
      - run:
          name: Test
          command: make test
      - run:
          name: Save image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish:
    executor: docker-publish
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Push image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            IMAGE_TAG="${CIRCLE_BUILD_NUM}"
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG

workflows:
  version: 2
  main:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
